### ISSUE TITLE
Call multiple phone numbers at once by separating your dial strings with the & character, not working

### ISSUE THREAD

**Issue by canivel** [rdegges/pycall#12]
Hi, tks for the great lib!
I'm trying to use it to send multiple calls, like the docs explain, to separate with & each string:

`
from pycall import CallFile, Call, Application

call = Call('SIP/serverts2/12129998888&SIP/serverts2/12127778888')
action = Application('Playback', 'hello-world')

c = CallFile(call, action)
c.spool()
`

But it returns a parse error in asterisk ... what Am I doing wrong? 

Tks

**Comment by rdegges** [comment]
What error is Asterisk giving you?

**Comment by canivel** [comment]
Tks for answering, follow the debug:

> asterisk*CLI> 
>     -- Attempting call on SIP/usmatrixts2/12129998888&SIP/usmatrixts2/12127778888 for application Playback(hello-world) (Retry 1)
> [Aug 16 11:34:08] ERROR[10271]: netsock2.c:305 ast_sockaddr_resolve: getaddrinfo("usmatrixts2/12127778888", "(null)", ...): Name or service not known
> [Aug 16 11:34:08] WARNING[10271]: acl.c:800 resolve_first: Unable to lookup 'usmatrixts2/12127778888'
> [Aug 16 11:34:08] WARNING[10271]: chan_sip.c:3415 proxy_update: Unable to locate host 'usmatrixts2/12127778888'
>   == Using SIP RTP CoS mark 5
> [Aug 16 11:34:08] WARNING[10273]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
>     -- Called usmatrixts2/12129998888&SIP/usmatrixts2/12127778888
> [Aug 16 11:34:08] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:09] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:11] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:15] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:23] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:39] WARNING[9932]: chan_sip.c:3776 __sip_xmit: sip_xmit of 0x7f250c004220 (len 909) to (null) returned -1: Invalid argument
> [Aug 16 11:34:40] WARNING[9932]: chan_sip.c:4060 retrans_pkt: Retransmission timeout reached on transmission 1051e1f5472b7a8b774d61bc79ac2169@200.196.22.8 for seqno 102 (Critical Request) -- See https://wiki.asterisk.org/wiki/display/AST/SIP+Retransmissions
> Packet timed out after 31999ms with no response
> [Aug 16 11:34:40] WARNING[9932]: chan_sip.c:4084 retrans_pkt: Hanging up call 1051e1f5472b7a8b774d61bc79ac2169@200.196.22.8 - no reply to our critical packet (see https://wiki.asterisk.org/wiki/display/AST/SIP+Retransmissions).
> [Aug 16 11:34:40] NOTICE[10271]: pbx_spool.c:413 attempt_thread: Call failed to go through, reason (0) Call Failure (not BUSY, and not NO_ANSWER, maybe Circuit busy or down?)
> [Aug 16 11:34:40] NOTICE[10271]: pbx_spool.c:416 attempt_thread: Queued call to SIP/usmatrixts2/12129998888&SIP/usmatrixts2/12127778888 expired without completion after 0 attempts
> asterisk*CLI>

**Comment by rdegges** [comment]
It looks like the error isn't your acll file format, but your SIP trunk. I think you've either defined your SIP trunk incorrectly, or haven't supplied the phone number in the correct format for your SIP trunk. You might want to try going to the #asterisk IRC channel and asking for more help there.

The callfile stuff looks good though =)

**Comment by canivel** [comment]
Tks, I will debug more, with only one it works fine, but when I add the & it brokes... anyways tks again for answer!

**Comment by rdegges** [comment]
You might want to try double checking the `usmatrixts2` trunk. The logs indicate that's where the problem is! Sorry I can't be more helpful :(
