### ISSUE TITLE
Regarding Environment Setup

### ISSUE THREAD

**Issue by prakhar21** [rdegges/pycall#13]
Hi, I am really excited about this project and can't wait to test it. Could you please provide the preparation steps in detail that are mentioned here docs.pycall.org/en/latest/usage.html#preparation
I have Ubuntu 14.04 as my base OS.

Thanks

**Comment by rdegges** [comment]
I'm terribly sorry, but that is simply out of scope for this project. Setting up Asterisk requires a lot of time, research, and there are many variables that come into play. It isn't reasonable to add all of that to this small library's documentation :(

**Comment by prakhar21** [comment]
@rdegges  If you could give some links that i can follow. I am doing research on my part. 

Thanks

**Comment by rdegges** [comment]
Definitely read through this book: http://cdn.oreilly.com/books/9780596510480.pdf It's one of the best references out there.
