### ISSUE TITLE
path.py >= 10.0 not working

### ISSUE THREAD

**Issue by fjbf** [rdegges/pycall#15]
With path.py = 10.0

python -c "import pycall"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pycall/__init__.py", line 8, in <module>
    from .callfile import CallFile
  File "/usr/local/lib/python2.7/dist-packages/pycall/callfile.py", line 11, in <module>
    from path import path
ImportError: cannot import name path

pip install -I path.py==9.1
Downloading/unpacking path.py==9.1
  Downloading path.py-9.1-py2.py3-none-any.whl
Installing collected packages: path.py
Successfully installed path.py
Cleaning up...

python -c "import pycall"

And now no errors

**Comment by rdegges** [comment]
I'd love to get a PR for this, pretty busy with other things at the moment! If you send one over, that'd help a ton! <3

**Comment by manzato** [comment]
@rdegges please check the PR #16 which should fix this

**Comment by manzato** [comment]
@rdegges we are hurting a bit with this issue, currently evaluating to pin the version to an older one. If you can, could you please check #16 which fixes this problem? Sorry to pester you

**Comment by rdegges** [comment]
Just released a new version to PyPI with this included. You're also listed as a contributor now. Thanks a bunch!
