### ISSUE TITLE
Offline Documentation!!

### ISSUE THREAD

**Issue by johndiego** [rdegges/pycall#20]
Offline documentation in http://docs.pycall.org/
Thanks guys

**Comment by rdegges** [comment]
Thanks for the heads up! Going to take a look. It appears that readthedocs made some DNS changes. I'll get that resolved.

**Comment by bjolivot** [comment]
doc seems to be here :
https://pycall.readthedocs.io/en/latest/

**Comment by e-Euler** [comment]
Documentation is down again at the docs subdomain.
